// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Carousel': typeof import("../components/Carousel.vue")['default'],
    'OneTimePass': typeof import("../components/OneTimePass.vue")['default'],
    'RichTextEditor': typeof import("../components/RichTextEditor.vue")['default'],
    'TheFooter': typeof import("../components/TheFooter.vue")['default'],
    'TheHeader': typeof import("../components/TheHeader.vue")['default'],
    'Thumbnail': typeof import("../components/Thumbnail.vue")['default'],
    'Banner': typeof import("../components/banner.vue")['default'],
    'LiwaConfig': typeof import("../components/liwaConfig.vue")['default'],
    'LiwaMsg': typeof import("../components/liwaMsg.vue")['default'],
    'LiwaPages': typeof import("../components/liwaPages.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyCarousel': typeof import("../components/Carousel.vue")['default'],
    'LazyOneTimePass': typeof import("../components/OneTimePass.vue")['default'],
    'LazyRichTextEditor': typeof import("../components/RichTextEditor.vue")['default'],
    'LazyTheFooter': typeof import("../components/TheFooter.vue")['default'],
    'LazyTheHeader': typeof import("../components/TheHeader.vue")['default'],
    'LazyThumbnail': typeof import("../components/Thumbnail.vue")['default'],
    'LazyBanner': typeof import("../components/banner.vue")['default'],
    'LazyLiwaConfig': typeof import("../components/liwaConfig.vue")['default'],
    'LazyLiwaMsg': typeof import("../components/liwaMsg.vue")['default'],
    'LazyLiwaPages': typeof import("../components/liwaPages.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const Carousel: typeof import("../components/Carousel.vue")['default']
export const OneTimePass: typeof import("../components/OneTimePass.vue")['default']
export const RichTextEditor: typeof import("../components/RichTextEditor.vue")['default']
export const TheFooter: typeof import("../components/TheFooter.vue")['default']
export const TheHeader: typeof import("../components/TheHeader.vue")['default']
export const Thumbnail: typeof import("../components/Thumbnail.vue")['default']
export const Banner: typeof import("../components/banner.vue")['default']
export const LiwaConfig: typeof import("../components/liwaConfig.vue")['default']
export const LiwaMsg: typeof import("../components/liwaMsg.vue")['default']
export const LiwaPages: typeof import("../components/liwaPages.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyCarousel: typeof import("../components/Carousel.vue")['default']
export const LazyOneTimePass: typeof import("../components/OneTimePass.vue")['default']
export const LazyRichTextEditor: typeof import("../components/RichTextEditor.vue")['default']
export const LazyTheFooter: typeof import("../components/TheFooter.vue")['default']
export const LazyTheHeader: typeof import("../components/TheHeader.vue")['default']
export const LazyThumbnail: typeof import("../components/Thumbnail.vue")['default']
export const LazyBanner: typeof import("../components/banner.vue")['default']
export const LazyLiwaConfig: typeof import("../components/liwaConfig.vue")['default']
export const LazyLiwaMsg: typeof import("../components/liwaMsg.vue")['default']
export const LazyLiwaPages: typeof import("../components/liwaPages.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
